# Week 4 Homework

# Matt Briskey

### Summarize the basic idea of logistic regression, support vector machines (SVM), and decision tree.

Logistic regression is one of the most widely used algorithms for classification in industry that tries to predict if an input if part of a particular class.  Training data is used to mimize the cost function. Logistics regression is also used to determine the weights of belonging to a particular class (how likely it will rain).

upport vector machines aims  to find a hyperplane that separates the data into different classes while maximizing the margin, which is the distance between the hyperplane and the nearest data points of each class.  The objective of using training data is to find the optimal hyperplane by solving an optimization problem.  SVM are an extension of the perceptron.

Decision trees breaks the data down into a series of questions and is therefore easy to interpret.  Based on the features in the training set, the decision tree model learns a series of questions to infer the class labels of the samples.  A deicision tree is typically pruned so that it doesn't overfit the data by having too deep of nodes.

### Read the section of Random Forest, and summarize the major steps.

A random forest is a group of decision trees.The idea behind a random forest is to average multiple (deep) decision trees that individually suffer from high variance, therefore building a more robust model that has a better generalization performance and is less susceptible to overfitting.  The general steps involved are:
1. Use random sampling with replacement (bootstrapped samples)
2. Train decision trees of each of the bootstrapped samples independently.  Randomly selected subsets of the features are used in each bootstrapped sample
3. A new data point is passed through each of the bootsrapped trees and the ending classification is jotted down
4. The classification with the most votes wins and that classification makes it into the aggregrate tree

### Why do we split samples into training and test set? What does the stratify mean?

Splitting the data between training and test data sets allows for generalization and performance evaluation.  The model needs to perform well on unseen data and the test data is used as a proxy for how well it will perfrom on other unseen data.  Additionally, we need to be able to evaluate the each model on independent data sets that aren't used in the training phase.  Lastly, using test data prevents the model from being overfit to align exclusively to the training data.  If the model performs significantly worse on the test set than on the training set, it suggests overfitting, indicating that the model may not generalize well to new data.

Stratifying refers to a technique used to ensure that the class distribution in the dataset is preserved in the training and test sets. When we stratify the data, we aim to maintain the same proportion of classes in both sets as in the original dataset.  Stratification is particularly useful when dealing with imbalanced datasets, where one class may be significantly underrepresented compared to others. By using stratified sampling, we ensure that both the training and test sets have a similar class distribution, which helps prevent biased model performance evaluation.

### Explain what are the bias-variance trade off and regularization.

The bias-variance trade off involves finding the right balance between bias and variance which are two sources of error in a model.  A model with high variance is caused by having too many parameters that lead to a model that is too complex
given the underlying data. Similarly, models can also suffer from underfitting (high bias), which means that our model is not complex enough to capture thepattern in the training data well and therefore also suffers from low performance on unseen data.

One way of finding a good bias-variance tradeoff is to tune the complexity of the model via regularization. Regularization is a very useful method to handle collinearity (high correlation among features), filter out noise from data, and eventually prevent overfitting. The concept behind regularization is to introduce additional information (bias) to penalize extreme parameter  values. The most common form of regularization is so-called L2 regularization.

### When do we use SVM's kernel method?

SVM's kernel method can be used for data that is nonlinear.  Kernel methods create nonlinear combinations of the original features to project them onto a higher-dimensional space via a mapping function where it becomes linearly
separable (a two dimensional dataset is transformed into a three dimensional dataset that is linearly separable).  

### Load the scikit-learn's Wine recognition dataset; separate 20% data as test data set; predict the wine quality using the 3 methods (logistic regression, support vector machines, decision tree), and print the accuracy in the test set of each method.

In [1]:
from sklearn import datasets
import numpy as np
import pandas as pd

df = datasets.load_wine()

X = df.data
y = df.target

In [2]:
print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [3]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [4]:
print(df.feature_names) # check the feature names

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [5]:
print(df.target_names) # list target names

['class_0' 'class_1' 'class_2']


In [6]:
# randomly split the X and y arrays into 20 percent test data and 80 percent training data 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2, 
    random_state=2,
    stratify=y
)

In [7]:
print('Labels counts in y:', np.bincount(y))
print('Labels counts in y_train:', np.bincount(y_train))
print('Labels counts in y_test:', np.bincount(y_test))

Labels counts in y: [59 71 48]
Labels counts in y_train: [47 57 38]
Labels counts in y_test: [12 14 10]


### Logistic Regression

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create an instance of the Logistic Regression model
logreg = LogisticRegression (solver='liblinear')

# Train the model on the training data
logreg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logreg.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))


Accuracy: 0.97


### Support Vector Machines

In [55]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Create an instance of the Support Vector Machine model
svm = SVC()

# Train the model on the training data
svm.fit(X_train, y_train)

# Make predictions on the test data
y_pred = svm.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))


Accuracy: 0.81


### Decision Tree

In [56]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Create an instance of the Decision Tree classifier
dt = DecisionTreeClassifier()

# Train the model on the training data
dt.fit(X_train, y_train)

# Make predictions on the test data
y_pred = dt.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))


Accuracy: 0.94
